services:
  pm2-web-ui-mongodb:
    container_name: pm2-web-ui-mongodb
    image: bitnami/mongodb:6.0.13
    user: root
    ports:
      - '${PM2_MONGODB_PORT}:27017'
    volumes:
      - './.volumes/db/mongo-volume:/bitnami/mongodb/data/db'
    environment:
      - 'MONGODB_ROOT_PASSWORD=${PM2_MONGODB_PASSWORD}'
    networks:
      - pm2-web-ui-network

networks:
  pm2-web-ui-network:
    driver: bridge
